COLUMN  "DATE EMBAUCHE"   FORMAT A15 
COLUMN  "FIN ESSAI"       FORMAT A20 
COLUMN  "FIN MOIS ESSAI"  FORMAT A15 
 

 SELECT   NOM,  
 TO_CHAR(EMBAUCHE,'DD-MM-YY')    "DATE EMBAUCHE",  
 TO_CHAR(NEXT_DAY(add_months(embauche,3),'VENDREDI'),'DAY DD-MM-YY') "FIN ESSAI",  
 TO_CHAR(LAST_DAY(add_months(embauche,3)),'DD-MM-YY')            "FIN MOIS ESSAI"
 FROM    EMP ;